name: RYALITY.
favicon: null
layout_spectrum: 0.1696138740517199
typography_spectrum: 0.10074661276303232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3622825413476676
  lightness: 0.8310026947874576
  saturation: 0.9152121820952743
  rhythmicContrast: 0.4091881744097918
purpose: []
